### ISSUE TITLE
Epic Marketplace

### ISSUE THREAD

**Issue by JakubHojsan** [cs-130/subletr#4]
## Epic: Marketplace
As a user, I want to interface (buyers/sellers or rather sublet-ers/sublet-ees) with other users in order to create a transaction for the intention of subletting.

Detailed Description
The platform will provide features such as a chat system, contract generation, checkout process, and the ability to view photos and descriptions of available sublets. Users will also have the option to search and sort sublets based on criteria including price, size, bedrooms, bathrooms, and roommate preferences.

## User Stories
- [x] #25  Given that I want to communicate with other users, then I need a chat feature.
- [x] Given that I want the experience to be seamless, I want the platform to auto-generate a contract that outlines the terms of the subletting arrangement, including rent, duration, and any additional conditions.
- [x] #32 Given that I want the experience to be seamless, I want the platform to be able auto-generate descriptions of my sublet so that I can quickly creating a listing without worrying about tedious writing.
- [x] Given that I am a user, I want to have a seamless checkout process that allows me to make a payment and confirm the subletting transaction.
- [x] #33 Given that I am a vigilant consumer, I want to be able to view photos and read descriptions of available sublets to help me make informed decisions.
- [x] (#14) Given that I have certain requirements, I want to be able to filter the listings based on various criteria such as price, size, number of bedrooms, number of bathrooms, and specific roommate preferences.
